[package]
name = "minesweeper-multiplayer"
version = "0.1.0"
authors = ["Will Cohen <willcohen3515@gmail.com>"]
edition = "2018"

[dependencies]
yew = "0.18"
rand = { version = "0.6.5", features = ["wasm-bindgen"] }
array2d = "0.2.1"
